// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5HEUZiyTn8OTNftyptzNA5w4MfukPOsw',
    appId: '1:1087614594522:web:e81e7cd06d9b0f61b1e4e3',
    messagingSenderId: '1087614594522',
    projectId: 'the-note-backend',
    authDomain: 'the-note-backend.firebaseapp.com',
    storageBucket: 'the-note-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ShtOS30aWtwO3NkX2vD2CQl93hb6_B8',
    appId: '1:1087614594522:android:39722c8933d49e11b1e4e3',
    messagingSenderId: '1087614594522',
    projectId: 'the-note-backend',
    storageBucket: 'the-note-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDITSj7JfBbzQ6uBHZIeI06f-m5djTV8BY',
    appId: '1:1087614594522:ios:887ad2a435477b20b1e4e3',
    messagingSenderId: '1087614594522',
    projectId: 'the-note-backend',
    storageBucket: 'the-note-backend.appspot.com',
    iosClientId: '1087614594522-dtbjibdck9drdadvc747uqt71vf5c6bi.apps.googleusercontent.com',
    iosBundleId: 'com.example.theNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDITSj7JfBbzQ6uBHZIeI06f-m5djTV8BY',
    appId: '1:1087614594522:ios:887ad2a435477b20b1e4e3',
    messagingSenderId: '1087614594522',
    projectId: 'the-note-backend',
    storageBucket: 'the-note-backend.appspot.com',
    iosClientId: '1087614594522-dtbjibdck9drdadvc747uqt71vf5c6bi.apps.googleusercontent.com',
    iosBundleId: 'com.example.theNotes',
  );
}
